name: Package

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  package-windows:
    name: Windows
    runs-on: windows-latest
    env:
      VULKAN_VERSION: "1.3.231.1"
      VULKAN_SDK: "C:/VulkanSDK/1.3.231.1"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Cache Vulkan SDK
        id: cache-vulkan
        uses: actions/cache@v2
        with:
          path: ${{ env.VULKAN_SDK }}
          key: vulkan-${{ env.VULKAN_VERSION }}
      - name: Install Vulkan SDK
        if: steps.cache-vulkan.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_VERSION }}/windows/VulkanSDK-${{ env.VULKAN_VERSION }}-Installer.exe" -OutFile vulkan.exe
          7z x -aoa vulkan.exe "-o$env:VULKAN_SDK" Lib

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package client --release --no-default-features

      - name: Package Artifacts
        run: |
          mkdir artifacts
          Move-Item -Path assets/* -Destination artifacts/
          Move-Item -Path target/release/*.exe -Destination artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: "artifacts/*"
