name: Package

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  package-windows:
    name: Windows
    runs-on: windows-latest
    env:
      VULKAN_VERSION: "1.3.231.1"
      VULKAN_SDK: "C:/VulkanSDK/1.3.231.1"
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Cache Vulkan SDK
        id: cache-vulkan
        uses: actions/cache@v4
        with:
          path: ${{ env.VULKAN_SDK }}
          key: vulkan-${{ env.VULKAN_VERSION }}
      - name: Install Vulkan SDK
        if: steps.cache-vulkan.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_VERSION }}/windows/VulkanSDK-${{ env.VULKAN_VERSION }}-Installer.exe" -OutFile vulkan.exe
          7z x -aoa vulkan.exe "-o$env:VULKAN_SDK" Lib share/vulkan/registry/vk.xml
